-- Autogenerated: do not edit this file

CREATE TABLE BATCH_JOB_INSTANCE  (
                                     JOB_INSTANCE_ID BIGINT  NOT NULL PRIMARY KEY ,
                                     VERSION BIGINT ,
                                     JOB_NAME VARCHAR(100) NOT NULL,
                                     JOB_KEY VARCHAR(32) NOT NULL,
                                     constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ENGINE=InnoDB;

CREATE TABLE BATCH_JOB_EXECUTION  (
                                      JOB_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
                                      VERSION BIGINT  ,
                                      JOB_INSTANCE_ID BIGINT NOT NULL,
                                      CREATE_TIME DATETIME(6) NOT NULL,
                                      START_TIME DATETIME(6) DEFAULT NULL ,
                                      END_TIME DATETIME(6) DEFAULT NULL ,
                                      STATUS VARCHAR(10) ,
                                      EXIT_CODE VARCHAR(2500) ,
                                      EXIT_MESSAGE VARCHAR(2500) ,
                                      LAST_UPDATED DATETIME(6),
                                      constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
                                          references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ENGINE=InnoDB;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS  (
                                             JOB_EXECUTION_ID BIGINT NOT NULL ,
                                             PARAMETER_NAME VARCHAR(100) NOT NULL ,
                                             PARAMETER_TYPE VARCHAR(100) NOT NULL ,
                                             PARAMETER_VALUE VARCHAR(2500) ,
                                             IDENTIFYING CHAR(1) NOT NULL ,
                                             constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
                                                 references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ENGINE=InnoDB;

CREATE TABLE BATCH_STEP_EXECUTION  (
                                       STEP_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
                                       VERSION BIGINT NOT NULL,
                                       STEP_NAME VARCHAR(100) NOT NULL,
                                       JOB_EXECUTION_ID BIGINT NOT NULL,
                                       CREATE_TIME DATETIME(6) NOT NULL,
                                       START_TIME DATETIME(6) DEFAULT NULL ,
                                       END_TIME DATETIME(6) DEFAULT NULL ,
                                       STATUS VARCHAR(10) ,
                                       COMMIT_COUNT BIGINT ,
                                       READ_COUNT BIGINT ,
                                       FILTER_COUNT BIGINT ,
                                       WRITE_COUNT BIGINT ,
                                       READ_SKIP_COUNT BIGINT ,
                                       WRITE_SKIP_COUNT BIGINT ,
                                       PROCESS_SKIP_COUNT BIGINT ,
                                       ROLLBACK_COUNT BIGINT ,
                                       EXIT_CODE VARCHAR(2500) ,
                                       EXIT_MESSAGE VARCHAR(2500) ,
                                       LAST_UPDATED DATETIME(6),
                                       constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
                                           references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ENGINE=InnoDB;

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT  (
                                               STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
                                               SHORT_CONTEXT VARCHAR(2500) NOT NULL,
                                               SERIALIZED_CONTEXT TEXT ,
                                               constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
                                                   references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ENGINE=InnoDB;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT  (
                                              JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
                                              SHORT_CONTEXT VARCHAR(2500) NOT NULL,
                                              SERIALIZED_CONTEXT TEXT ,
                                              constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
                                                  references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ENGINE=InnoDB;

CREATE TABLE BATCH_STEP_EXECUTION_SEQ (
                                          ID BIGINT NOT NULL,
                                          UNIQUE_KEY CHAR(1) NOT NULL,
                                          constraint UNIQUE_KEY_UN unique (UNIQUE_KEY)
) ENGINE=InnoDB;

INSERT INTO BATCH_STEP_EXECUTION_SEQ (ID, UNIQUE_KEY) select * from (select 0 as ID, '0' as UNIQUE_KEY) as tmp where not exists(select * from BATCH_STEP_EXECUTION_SEQ);

CREATE TABLE BATCH_JOB_EXECUTION_SEQ (
                                         ID BIGINT NOT NULL,
                                         UNIQUE_KEY CHAR(1) NOT NULL,
                                         constraint UNIQUE_KEY_UN unique (UNIQUE_KEY)
) ENGINE=InnoDB;

INSERT INTO BATCH_JOB_EXECUTION_SEQ (ID, UNIQUE_KEY) select * from (select 0 as ID, '0' as UNIQUE_KEY) as tmp where not exists(select * from BATCH_JOB_EXECUTION_SEQ);

CREATE TABLE BATCH_JOB_SEQ (
                               ID BIGINT NOT NULL,
                               UNIQUE_KEY CHAR(1) NOT NULL,
                               constraint UNIQUE_KEY_UN unique (UNIQUE_KEY)
) ENGINE=InnoDB;

INSERT INTO BATCH_JOB_SEQ (ID, UNIQUE_KEY) select * from (select 0 as ID, '0' as UNIQUE_KEY) as tmp where not exists(select * from BATCH_JOB_SEQ);

create table tbl_restaurant
(
    id                   bigint auto_increment
    primary key,
    apv_cancel_ymd       varchar(8)    null comment '인허가취소일자',
    apv_perm_ymd         varchar(8)    null comment '인허가일자',
    bdng_own_se_nm       varchar(200)  null comment '건물소유구분명',
    bplc_nm              varchar(200)  null comment '사업장명',
    clg_enddt            varchar(8)    null comment '휴업종료일자',
    clg_stdt             varchar(8)    null comment '휴업시작일자',
    dcb_ymd              varchar(8)    null comment '폐업일자',
    dtl_state_gbn        varchar(4)    null comment '상세영업상태코드',
    facil_tot_scp        varchar(4000) null comment '시설총규모',
    fcty_owk_ep_cnt      int           null comment '공장사무직직원수',
    fcty_pdt_job_ep_cnt  int           null comment '공장생산직직원수',
    fcty_sil_job_ep_cnt  int           null comment '공장판매직직원수',
    hoff_ep_cnt          int           null comment '본사직원수',
    homepage             varchar(500)  null comment '홈페이지',
    isre_am              int           null comment '보증액',
    jt_upso_asgn_no      varchar(20)   null comment '전통업소지정번호',
    jt_upso_main_edf     varchar(20)   null comment '전통업소주된음식',
    last_mod_ts          varchar(14)   null comment '최종수정시점',
    lv_se_nm             varchar(200)  null comment '등급구분명',
    man_eip_cnt          int           null comment '남성종사자수',
    mgt_no               varchar(40)   null comment '관리번호',
    mon_am               int           null comment '월세액',
    mult_usn_upso_yn     varchar(1)    null comment '다중이용업소여부 - Y/N',
    opn_sf_team_code     char(7)       null comment '개방자치단체코드',
    opn_svc_id           char(10)      null comment '개방서비스아이디',
    pos_x                char(20)      null comment '좌표정보(x)',
    pos_y                char(20)      null comment '좌표정보(y)',
    rdn_post_no          varchar(7)    null comment '도로명우편번호',
    rdn_whl_addr         varchar(200)  null comment '도로명전체주소',
    ropn_ymd             varchar(8)    null comment '재개업일자',
    row_num              bigint        null comment '번호',
    site_area            varchar(18)   null comment '소재지면적',
    site_post_no         varchar(7)    null comment '소재지우편번호',
    site_tel             varchar(100)  null comment '소재지전화',
    site_whl_addr        varchar(500)  null comment '소재지전체주소',
    snt_uptae_nm         varchar(200)  null comment '위생업태명',
    tot_ep_num           int           null comment '총직원수',
    trd_state_gbn        varchar(2)    null comment '영업상태구분코드',
    trdp_jubn_se_nm      varchar(100)  null comment '영업장주변구분명',
    update_dt            datetime      null comment '데이터갱신일자 - API에 변경점 적용시점',
    update_gbn           char          null comment '데이터갱신구분 - U(Update)/I(Insert)',
    uptae_nm             varchar(100)  null comment '업태구분명',
    wm_eip_cnt           int           null comment '여성종사자수',
    wtr_sply_facil_se_nm varchar(200)  null comment '급수시설구분명',
    constraint unique_restaurant_key
    unique (opn_svc_id, opn_sf_team_code, mgt_no)
);

