spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/danal_test?connectTimeout=30000&socketTimeout=30000
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

csv-file-path: "data/full_test.csv"
chunk-size: "5"

logging:
  level:
    #    org.springframework.jdbc: debug
    kr.co.danal: debug
